"""
Extract K[2] Base64 map.
K[2] keys are generated by a[4](expr), where a[4] is a Hex Decoder using K[5].
Values are number expressions.
"""
import re
import math

content = open(r'd:\dec bot2\max_security_mode\print_hi.lua', 'r', encoding='utf-8', errors='ignore').read()

def lua_eval(expr):
    try:
        # Simplistic eval for arithmetic
        expr = expr.replace('(', ' ( ').replace(')', ' ) ')
        return int(eval(expr, {"__builtins__": None, "math": math}))
    except:
        return 0

# 1. Extract K[5] Hex Map (16 entries)
# We already parsed this in decrypt_max_v2.py, but let's hardcode the logic or reuse extraction
# For this script, I'll assume I can extract it or I'll just look for the block.
# Helper: The K[5] map extracted in a previous step was:
# 0->9, 1->11, 2->10, ...
# Wait, that was the SECOND K[5] (Layer 2b map in my old terminology).
# Yes, that K[5] is the one used by a[4].
# Let's re-extract it dynamically to be safe.

def extract_k5_map(content):
    # Find K[5] block
    match = re.search(r'K\[5\]=\{(.*?)\}', content, re.DOTALL)
    if not match: return {}
    block = match.group(1)
    
    # Parse entries: [a[12][a[5](a[2](IDX)...)]] = VAL
    # We cheat: we know the VALUES are 0-15.
    # The KEYS are 1-byte strings.
    # We can use the logic from 'extract_k5_correct.py' or 'decrypt_max_v2.py'.
    # Actually, simpler: define the mapping if we know it?
    # But it changes with seed?
    # No, it's static for the file.
    # But finding the KEY requires running a[5]/a[2].
    # That is complex.
    
    # Alternative: The KEYS are Standard Hex Chars (0-9, A-F)?
    # Wait, in the Logic: a[4] does hex decode.
    # e[4] = K[5][byte].
    # So K[5] maps HexBytes -> Nibbles.
    # If we assume 0..9 -> 0..9 etc?
    # No, it's obfuscated.
    # But we EXTRACED it in Step 3326.
    # 0->9, 1->11, 2->10, 3->4, 4->5, 5->7, 6->2, 7->3, 8->6, 9->15
    # A->8, B->12, C->14, D->13, E->1, F->0
    # I will HARDCODE this map for now for 'a[4]' emulation.
    # This specific map is for 'print_hi.lua' / '9874...'.
    # Wait, Step 3326 output was for 'decrypt_max_v2.py' running on '9874...'.
    # If 'print_hi.lua' is the same file (renamed), then it works.
    
    return {
        ord('0'): 9, ord('1'): 11, ord('2'): 10, ord('3'): 4, ord('4'): 5,
        ord('5'): 7, ord('6'): 2, ord('7'): 3, ord('8'): 6, ord('9'): 15,
        ord('A'): 8, ord('B'): 12, ord('C'): 14, ord('D'): 13, ord('E'): 1, ord('F'): 0
    }

k5_map = extract_k5_map(content)

# 2. Extract a[7] (Layer 1 output) to use in a[4]?
# No, a[4] is CALLED with constants in K[2] definition.
# K[2] = { [a[4](NUM_EXPR)] = VAL_EXPR ... }
# Wait, a[4] takes a NUMBER? (Index into a[7]?)
# Code: `a[4]=function(K) ... end`.
# Usage: `a[4](number)`.
# Inside a[4]: `V[2]=K[8][K]`. `K[8]` is `a[3]`.
# So `a[4]` decrypts `a[3][K]`.
# `a[3]` table is defined BEFORE `K[2]`.
# `a[3]={a[4](...), a[4](...), ...}`.
# Wait, recursion?
# `a[3]={...}` calls `a[4]`. `a[4]` calls `a[3]`?
# No.
# `a[4]=function(K)...` defines function.
# `a[3]={a[4](idx)...}` calls `a[4]` with INDICES.
# Inside `a[4]`, it uses `K[8]`. `K[8]=a[3]`.
# BUT `a[3]` is being constructed!
# Lua table construction: `a[3]` is not fully built yet?
# Or `K[8]` is bound to `a[3]` which is valid?
# Usually `a[3]` is `a[7]` in other scripts.
# Here `K[8]` is `a[3]`.
# But `a[3]` is being populated.
# If `K[8][idx]` is accessed, `idx` must exist.
# The indices passed to `a[4]` are huge numbers? `-154147...`.
# Maybe these are not indices into `a[3]`?
# Maybe `a[4]` treats input K as something else?
# Lua: `V[2]=K[3][H]` (in a[5] loop).
# `a[4]` arguments...
# Let's check `a[4]` definition.
# `a[4]=function(K) local H={} H[1]=K return a[6][H[1]+offset] end` -> This is `a[10]`.
# `a[4]=function(K) ... ` - The long Hex Decode function from `k5_dump.txt` line 2.
# `V[2]=K` ?? No.
# `K` is argument.
# `V[3]=K`?
# In `k5_dump.txt` line 2:
# `for H=..., #K[8] ... do ... V[3]=K[8][H] ... if K[6](V[3])==a[12]...` (Note: K[6] is type).
# `a[4]` is defined implicitly as the function in `a[3]={...}`??
# `a[3]={a[4](...)}`.
# Where is `a[4]` DEFINED?
# `a[4]=function(K) ... end` is NOT in the dump.
# The dump starts `=== INNER K[5] ...`.
# Inner K[5] is inside `a[4]`!
# `a[4]=function(K) ... K[5]={...} ... end`.
# So `a[4]` is the function wrapping `K[5]`.
# `a[4]` logic:
# `local V={} V[1]=K`.
# `V[3]=K[8][V[1]]`.
# So `a[4]` takes an INDEX `K`. It retrieves string from `K[8]` at that index.
# `K[8]` is `a[3]`.
# But `a[3]` is being defined!
# If `a[3]` is being defined, `K[8]` (alias to old `a[3]`?)
# `K[8]=a[3]`.
# Is `a[3]` defined BEFORE `a[4]` runs?
# In `k5_dump.txt`:
# `K[1]=math[a[4]...]`.
# `K[4]=table[a[4]...]`.
# `K[8]=a[3]`.
# `K[3]=table[...]`.
# `for H=..., #K[8] ... do` -> This loop iterates `K[8]`.
# So `K[8]` (a[3]) MUST be populated.
# Where is `a[3]` populated?
# `a[3]={a[4](...), ...}`.
# This looks like `a[3]` calls `a[4]` to populate itself.
# But `a[4]` USES `a[3]` (K[8]).
# This is circular unless `a[3]` contains UN-DECRYPTED strings initially?
# And `a[4]` DECRYPTS them in-place?
# `a[3]` definition line: `a[3]={a[4]...}`.
# This constructs `a[3]` with RESULTS of `a[4]`.
# `a[4]` returns a string.
# So `a[3]` contains decrypted strings.
# But `a[4](idx)` reads `K[8][idx]`.
# `K[8]` must be the ENCRYPTED table.
# `a[3]` is the DECRYPTED table?
# Maybe `a[7]` is the Encrypted Table.
# And `K[8]` is mapped to `a[7]`?
# `K[8]=a[3]`.
# This is confusing.

# Let's look at `decrypt_max_v2.py` line 300+ again.
# `a7_layer1` (Stream Cipher Output).
# `a[7]` is `a[12][...]`.
# Text extraction says `a[3] = { a[4](...) ... }`.
# `a[4]` MUST be the function that gets data from `a[7]`?
# `get_a7_val(idx_expr)` in my script.
# `real_idx = idx - (...)`.
# `a7_final[real_idx]`.
# So `a[4]` maps Index -> `a[7]` Entry.
# This assumes `a[4]` logic is simply "get from a[7]".
# But `k5_dump.txt` shows `a[4]` has `K[5]` inside it and does loops.
# So `a[4]` DOES DECRYPTION.
# And it reads from `a[7]`?
# If `K[8]` is `a[7]`.
# `V[3]=K[8][V[1]]`.
# Then `a[4]` decrypts `a[7][idx]`.
# That makes sense. `K[8]` should be `a[7]`.
# But `count_k5s.py` shows `K[8]=a[3]`.
# `K[8]=a[3]` appears AFTER `a[3]={...}`?
# No, `a[3]={...}` appears AFTER the Inner Loop.
# My dump lines order:
# 1. Inner Loop (lines 14-27). (This loop uses `K[8]` and `a[3]`).
# 2. `a[3]={...}` (lines 28-55).
# 3. `K[8]=a[3]` (line 58).
# Wait, `K[8]=a[3]` is assigned AFTER `a[3]` is built?
# Then who used `K[8]`?
# The `for H=... do` loop (lines 59+) uses `K[8]`.
# This loop uses `a[4]` logic? No, it uses `K[5]` logic directly?
# The loop (lines 59-75) performs the decodes IN PLACE on `K[8]`.
# `K[8][V[1]]=K[3](H[5])`. `K[3]` is `table.concat`.
# So this loop decrypts `a[3]` in place.
# `a[3]` is initialized with `a[4](...)`.
# `a[4]` calls are: `a[4](-154...)`.
# What does `a[4]` DO?
# `a[4]` is defined somewhere.
# `k5_dump.txt` line 123 (at end): `a[4]=function...`.
# It's NOT in the dump!
# `count_k5s.py` dump ended at line 122.
# `a[4]` is defined just before `do local K={}` according to my dump script logic.
# My dump script missed `a[4]` definition?
# "It's 'K[5]={' before a[4]".
# I dumped text around K[5].
# I need `a[4]` source code.

# But I know `a[4]` corresponds to extracting data from `a[7]`.
# My `decrypt_max_v2.py`: `get_a7_val`.
# Indices match `a[4]` calls.
# So `a[3]` is populated with `a[7]` items.
# `a[7]` items are results of `a[12][...]`.
# `a[12]` calls `K[6]` which calls `a[5]` (Layer 1).
# So `a[7]` items are Layer 1 Output (Byte Shifted Strings).
# `a[3]` gets these items.
# THEN the loop (lines 59-75) runs over `a[3]`.
# This loop does:
# 1. Byte Shift (Layer 2). `e[4]=e[4]-40`.
# 2. Base64 Decode (Layer 2b). Using `K[2]`.
# `K[2]` contains `a[4](...)` keys.
# `a[4]` calls here refer to `a[4]` function.
# BUT `a[3]` calls `a[4]` too.
# So `a[4]` behaves differently?
# No. `a[4]` returns a STRING.
# In `a[3]`: `a[3]={ string, string, ... }`.
# In `K[2]`: `keys` are strings. `values` are numbers.
# So `a[4]` returns strings.
# `a[4]` fetches strings from `a[7]`.
# So `K[2]` keys are Strings from `a[7]`.
# AND `a[3]` entries are Strings from `a[7]`.
# AND `a[6]` entries are Strings from `a[7]`.
# Everything comes from `a[7]`.

# `a[7]` contains EVERYTHING.
# Some `a[7]` entries are Map Keys.
# Some are Map Values? No, map values are numbers.
# Some are Data.

# So, to build `K[2]`, I need to:
# 1. Identify which `a[7]` entries are used as keys.
#    (Scan `K[2]={[a[4](IDX)] = VAL}` assignments).
# 2. Retrieve those `a[7]` entries.
#    (Using my `decrypt_a5` -> `get_a7` logic).
#    (These entries should be -40 shifted Base64 alphabet chars).
#    Wait, `K[2]` keys must be CHARS?
#    Base64 map maps Chars -> Values.
#    So `a[4](IDX)` MUST returns a single char string.
#    This implies `a[7]` entry at IDX is a single char.
#    If `a[7]` is -40 shifted: `Xqee`.
#    This is 4 chars.
#    `K[2]` key `Xqee` -> Value?
#    If `K[2]` has 64 entries.
#    Maybe `K[2]` keys ARE `Xqee`?
#    If `a[7]` contains `Xqee`.
#    Logic: `z[1]=K[6](V[3]...)` (Get 1 char of data string).
#    `z[2]=K[2][z[1]]`.
#    Lookup `z[1]` (1 char) in `K[2]`.
#    So `K[2]` keys MUST be 1 char.
#    So `a[4](IDX)` used in `K[2]` def MUST return 1 char.
#    So `a[7][IDX]` MUST be 1 char.
#    But `a[3]_dump.txt` shows `a[3]` (which is `a[7]`) has `Xqee` (len 4).
#    So `a[7]` has multi-byte strings.
#    But `K[2]` keys must be single byte.
#    So SOME `a[7]` entries are single byte.
#    (e.g. `A0...` decodes).
#    Wait, `Xqee` is Layer 1 output.
#    If I shift `X` (-40) -> `0` (Hex 30).
#    Is `0` a single char? Yes.
#    So if `a[7]` entry is `X`, it becomes `0`.
#    But `Xqee` is 4 chars.
#    Maybe `a[4]` takes a substring?
#    No `a[4]` returns `a[6][...]`.
#    Wait, `a[6]` is different.
#    `a[4]` returns `a[7]` item.
#    If `a[7]` item is `X`, `K[2]` key is `X`.
#    Then `K[2][X]` = Value.
#    Later, `V[3]` (data string) has char `c`.
#    Logic: `e[4]=e[4]-40`.
#    `c` is shifted. `c' = c - 40`.
#    `HexDecode(c')`.
#    `K[2]` logic?
#    Inner Loop Lines 22-24:
#    `z[1]= char`.
#    `z[2]=K[2][z[1]]`.
#    It does NOT shift `z[1]` before lookup!
#    It uses `z[1]` DIRECTLY.
#    BUT `V[3]` was Shifted in the previous loop (lines 16-21).
#    Lines 16-21: `for z... do ... e[4]=byte-40 ... K[4](H[1], char(e[4])) ... end`.
#    `V[3]=concat(H[1])`.
#    So `V[3]` IS shifted.
#    So `z[1]` IS shifted char.
#    So `K[2]` keys are SHIFTED chars.
#    e.g. `0` (from `X`-40).
#    So `K[2]` keys are `0-9, A-Z, a-z...`.
#    So `a[4]` calls in `K[2]` def must return `0`, `1`, `A`...
#    So `a[7]` entries referenced by `a[4]` in `K[2]` def must be `0`, `1`, `A`...
#    But `a[7]` holds Layer 1 output (UNSHIFTED).
#    If `a[7]` holds `X`.
#    `a[4]` returns `X`.
#    `K[2][X] = Val`.
#    Map has key `X`.
#    Code uses `z[1]` (shifted `X` -> `0`).
#    `K[2][0]`.
#    Mismatch!
#    Map key is `X`. Lookup is `0`.
#    This implies `a[7]` entries used for `K[2]` are ALREADY SHIFTED?
#    Or `V[3]` is NOT shifted?
#    Lines 16-21 Update `V[3]`.
#    `V[3] = K[3](H[1])`.
#    Yes, `V[3]` is overwritten with Shifted String.
#    So Lookup uses Shifted Char.
#    So Map Keys MUST be Shifted Chars.
#    So `a[4]` MUST return Shifted Chars.
#    But `a[4]` returns `a[7]` (Unshifted).
#    So `a[7]` entries used for Map MUST be `0, 1, ...`.
#    But `a[7]` entries come from Layer 1.
#    If Layer 1 produces `0`, then `X` (88) is not `0` (48).
#    This implies `a[7]` contains the TARGET Base64 Alphabet (`0-9...`).
#    And the DATA `a[7]` (like `Xqee`) contains `X, q, e`.
#    Shift `X` -> `0`.
#    Map `0` -> Val.
#    So Map needs Key `0`.
#    So `a[7]` map-entry must be `0`.
#    So Layer 1 must produce `0` for map entries.
#    And `X` for data entries.
    
#    This is consistent!
#    Layer 1 produces:
#    - Data: `X` (88).
#    - Map Keys: `0` (48).
#    So `a[7]` contains a mix of Shifted and Unshifted?
#    No. Data `X` needs shift to `0`. `0` is the decoded char.
#    The Map maps `0` -> Value.
#    So Map Keys are the DECODED (Shifted) characters.
#    So `a[7]` entries for Map Keys essentially store the Alphabet.
#    `a[7][k] = '0'`.
#    `K[2]['0'] = 0`.
#    `a[7][j] = 'X'`.
#    Cycle: `X` - 40 -> `0`. Lookup `K[2]['0']` -> 0.
#    Correct.
    
#    So `a[7]` MUST contain the Base64 Alphabet (`0-9, A-Z...`).
#    So I need to check if `a[7]` contains single chars `0, 1, ...`.
#    My `a[3]` dump showed 28 single chars: `Y, 7, J, p, /, T, 0, =...`.
#    These are Valid Base64 chars.
#    So `a[7]` DOES contain the alphabet.
    
#    So why did I get garbage `Xqee`?
#    `X` (88) -> `0` (48).
#    `q` (113) -> `I` (73).
#    `e` (101) -> `=` (61).
#    `e` (101) -> `=` (61).
#    `Xqee` -> `0I==`.
#    This IS valid Base64!
#    It's a Base64 string!
#    `0I==` decodes to ...
#    `0` (52), `I` (8).
#    `52` (110100), `8` (001000).
#    `110100 001000 ...`.
#    So `Xqee` IS Decodable Data.
    
#    The problem is My `decrypt_max_v2.py` logic:
#    It tried Hex Decode on `Xqee`. `X` is not Hex. Fails.
#    It tried Layer 2b (Hex) on `Xqee`. `X` is not Hex. Fails.
#    So it remained `Xqee`.
    
#    The CORRECT pipeline:
#    1. Shift -40. `Xqee` -> `0I==`.
#    2. Base64 Decode `0I==` -> Binary.
    
#    So I just need to implement this pipeline!
#    And I need the Base64 Map (`K[2]`).
#    The Map Keys are `a[7]` entries.
#    The Map Values are `...` (numbers).
    
#    My `extract_k2_base64.py` needs to:
#    1. Parse `K[2]={[a[4](idx)]=val}`.
#    2. Parse `idx`, `val`.
#    3. Get `a[7][idx]` (Key).
#    4. Store Key -> Val.
    
#    I need `a[7]`.
#    I can generate `a[7]` using `decrypt_a5` and `a[1]` (using `decrypt_max_v2.py` logic).
#    Then build map.
#    Then decrypt data.

#    ONE DETAIL: `extract_k5_map` above uses MY `decrypt_max_v2.py` K[5] (Hex map).
#    Is `K[5]` involved?
#    No. `K[5]` was involved in the `for ... do` loop in Lua (lines 16-21).
#    My previous analysis said `K[5]` is used in `a[4]`.
#    `a[4]` definition (not in dump) used `K[5]`.
#    If `a[4]` reads `a[7]`, does it use `K[5]`?
#    Probably not. `a[4]` is likely just `return a[7][idx]`.
#    Or `return a[6][...]`? (Line 123 snippet: `a[10]=... a[6][...]`).
#    Wait, `a[4]` logic in my previous 'print_hi.lua' analysis:
#    `a[4]` did Hex Decode?
#    `extract_layer4.py` Step 3192: `a[4]=function(K)... K[5][K[8]...]`.
#    It did Hex Decode.
#    This implies `a[7]` (K[8]) is HEX ENCODED.
#    But I just proved `a[7]` is SHIFTED BASE64 (`Xqee`).
#    Contradiction.
    
#    Maybe there are TWO DIFFERENT `a[4]` functions?
#    Overwritten?
#    Or I confused function names.
#    In `k5_dump.txt`, `K[5]={...}` (Layer 2b) uses `a[4]`.
#    `[a[4]...]=...`.
#    This `a[4]` MUST produce strings.
#    If `a[7]` is `Xqee`. Hex Decode fails.
#    Unless `a[4]` refers to the "Get a[7] Entry" function?
#    In `decrypt_max_v2.py`: `get_a7_val`.
#    I assumed `a[4]` IS `get_a7_val`.
    
#    Let's assume `a[4]` simply retrieves `a[7]` entry.
#    (Maybe `a[7]` entries ARE just keys?).
    
#    Wait, `Xqee` (len 4) is in `a[3]`.
#    `a[3]` contains `a[7]` entries.
#    `K[2]` keys are `len=1` entries in `a[3]` (e.g. `0`, `I`).
#    `a[3]` ALSO contains `Xqee`.
#    `Xqee` is NOT a key. It's valid data.
#    So `a[3]` contains BOTH Keys and Data.
#    This is standard.
    
#    So `extract_k2_base64.py` needs `a[7]`.
#    I will import `a[7]` generation from `decrypt_max_v2.py`.
    
#    Actually, I can just UPDATE `decrypt_max_v2.py` directly.
#    It already generates `a[3]` (which is `a[7]`).
#    I just need to Add "Build K[2]" step using `a[3]`.
#    Then "Decrypt a[3] Data" step.
    
#    `K[2]` construction:
#    Regex `K\[2\]=\{` ... parse entries ...
#    Entry: `[a[4](expr)] = val`.
#    `a[4](expr)` -> `a[3][expr]`. (Or `a[7]`).
#    `val` -> eval.
#    Map `string -> int`.
    
#    Then Decrypt `a[3]` loop.
#    For each entry `s` in `a[3]`:
#      `s_shifted = shift(s, -40)`
#      `decoded = base64_decode(s_shifted, K[2])`
#      `final.append(decoded)`
    
#    This seems correct.
    
    pass

